routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::auth();
Route::get('/', 'PageController@index')->name('home');
Route::get('/contact', 'PageController@contact')->name('contact');

Route::get('/admin', 'PageController@adminHome')->middleware('manager')->name('admin');



Route::prefix('admin-users-managment')->namespace('Admin')->name('admin.')->middleware('admin')->group( function () // ->middleware('manager') php artisan make:middleware manager
{
    Route::resource('users', 'UsersController');
});


Route::prefix('roles-managment')->namespace('Admin')->name('admin.')->middleware('manager')->group( function () //php artisan make:middleware manager
{
    Route::resource('roles', 'RolesController');
});


Route::prefix('admin-posts-managment')->namespace('Admin')->name('admin.')->middleware('manager')->group( function ()
{
    Route::resource('posts', 'PostsController');
    Route::get('/todayPosts','PostsController@getToday')->name('todayPosts');
    Route::post('/selectDayPosts','PostsController@selectDayPosts')->name('selectDayPosts');
});


Route::prefix('admin-categories-managment')->namespace('Admin')->name('admin.')->middleware('manager')->group( function ()
{
    Route::resource('categories', 'CategoryController');
});


Route::prefix('user-commentsAndPost')->namespace('User')->name('user.')->middleware('auth')->group( function ()
{
    Route::get('/create', 'PostsController@create')->name('create');
    Route::post('/store', 'PostsController@store')->name('store');
    Route::get('/show/{post}', 'PostsController@show')->middleware('auth')->name('show');
    Route::post('/commentsStore/{post}', 'CommentsController@store')->name('commentsStore');

});


Route::prefix('userSection')->namespace('User')->name('userSection.')->middleware('auth')->group( function ()
{
    Route::resource('posts','UserPostController');
});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class Post extends Model
{

    protected $fillable =
    [
        'title',
        'content',
        'slug',
        'status',
        'user_id',
    ];


    protected $with=
    [
        'comments',
        'categories',
        'images',
        'user',
    ];


    public function scopeSelectDay($query,$day) // il primo parametro è già implementato. Gli scope servono per richiamare le query, in modo da non doverle scrivere piu' volte
    {
        $query = $query->withCount(['categories','comments']);

        $tomorrow = $day->clone()->addDays(1);
        return $query = $query->where('created_at','>=',$day)->where('created_at','<=',$tomorrow)->get();

    }


    public function getCheckBelongAttribute()
    {
        $id = Auth::id();

        $user = $this->user()->first();

        if($user->id == $id)
        {
            return true;
        }
        else
        {
            return false;
        }
    }


    public function categories()
    {
        return $this->belongsToMany('App\Models\Category','category_post','post_id','category_id')->withTimestamps();
    }


    public function user()
    {
        return $this->belongsTo('App\User');
    }


    public function comments()
    {
        return $this->hasMany('App\Models\Comment','post_id');
    }


    public function images()
    {
        return $this->hasMany('App\Models\Image','post_id');
    }




    public function getRouteKeyName()
    {
        return 'slug';
    }

}

app/Http/Controllers/Admin/PostsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\PostEditRequest;
use App\Http\Requests\PostFormRequest;
use App\Models\Category;
use App\Models\Image;
use App\Models\Post;
use App\Traits\ImgManageTrait;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class PostsController extends Controller
{
    use ImgManageTrait;

    public function getToday()
    {

        $posts = Post::selectDay(Carbon::today());

        return view('admin.posts.today',compact('posts'));
    }

    public function selectDayPosts(Request $request)
    {
        $day = $request->dayPost;

        $carbonDate = Carbon::parse($day);

        $posts = Post::selectDay($carbonDate);

        return view('admin.posts.today',compact('posts'));
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::with('categories')->get();

        return view('admin.posts.index',compact('posts'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {

        if(!$post)
        {
            $errors =
            [
                'error_message' => 'Post non trovato'
            ];
            session()->flash('error',$errors);
            return redirect()->back();
        }

        $categories = Category::all();
        $selectedCategories = $post->categories->pluck('id')->toArray();
        return view('admin.posts.edit',compact('post','categories','selectedCategories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PostEditRequest $request, Post $post)
    {

        try
        {
            DB::beginTransaction();

                $post->title = $request->title;
                $post->content = $request->content;


                $post->categories()->sync($request->categories);

                if($request->hasFile('imageEdit'))
                {

                    $image = Image::where('post_id',$post->id)->firstOrFail();
                    $this->editImage($request->imageEdit,$post,$image );
                }

                if($request->hasFile('imageAdd'))
                {
                    $this->addImage($request->imageAdd, $post);
                }

                $updated = $post->save();

            DB::commit();

                session()->flash('success',('Post mofificato con successo'));
                return redirect()->route('admin.posts.index');
        }
        catch(\Exception $e)
        {
            $errors =
            [
                'error_message' => 'Errore nella modifica del post',
            ];
            session()->flash('error',($errors));
            return redirect()->route('admin.posts.index');
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        try
        {
            DB::beginTransaction();

                foreach($post->images as $image)
                {
                    if(file_exists( public_path('storage/'.$image->title) ) )
                    {
                        unlink(public_path('storage/'.$image->title));
                    }
                }
                Image::where('post_id',$post->id)->delete();
                $deleted = $post->delete();


            DB::commit();

                session()->flash('success',('Post cancellato con successo'));
                return redirect()->route('admin.posts.index');
        }
        catch(\Exception $e)
        {
            $errors =
            [
                'error_message' => 'Errore nella rimozione del post',
            ];
            session()->flash('error',($errors));
            return redirect()->route('admin.posts.index');
        }

    }
}

app/Http/Controllers/User/PostsController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Http\Requests\PostFormRequest;
use App\Models\Category;
use App\Models\Image;
use App\Models\Post;
use App\Traits\ImgManageTrait;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Validation\Rules\Unique;

class PostsController extends Controller
{

    use ImgManageTrait;


    public function create()
    {
        try
        {
            DB::beginTransaction();

                $categories = Category::all();

            DB::commit();

                return view('post.create',compact('categories'));
        }
        catch(\Exception $e)
        {

            $errors =
            [
                'error_message' => 'Errore nella creazione del post',
            ];
            session()->flash('error',($errors));
            return redirect()->route('home');
        }
    }


    public function store(PostFormRequest $request)
    {

        try
        {
            DB::beginTransaction();

                $user = Auth::user();

                $post = $user->posts()->create(
                [
                    'title'     => $request->title,
                    'content'   => $request->content,
                    'slug'      => uniqid(),
                ]);

                $post->categories()->sync($request->categories);

                if($request->hasFile('image'))
                {
                    $this->addImage($request->image, $post);
                }

            DB::commit();

                session()->flash('success',('Post creato con successo'));
                return redirect()->route('home');
        }
        catch(\Exception $e)
        {
            $errors =
            [
                'error_message' => 'Errore nella creazione del post',
            ];
            session()->flash('error',($errors));
            return redirect()->route('home');
        }

    }


    public function show( Post $post)
    {

        if(!$post)
        {
            $errors =
            [
                'error_message' => 'Post non trovato'
            ];
            session()->flash('error',$errors);
            return redirect()->route('home');
        }

        return view('post.show',compact('post'));
    }
}

resources/views/admin/posts/edit.blade.php
@extends('layouts.app')

@section('content')
  <div class="container col-md-10 col-md-offset-2">
        <div class="mt-5 card">
            <div class="card-header ">
                <h5 class="float-left">Edit a post</h5>
                @include('admin.components.redirect')
                <div class="clearfix"></div>
            </div>
            <div class="mt-2 card-body">
                <form method="post" action="{{ route('admin.posts.update',$post) }}"  enctype="multipart/form-data">
                    @csrf
                    @method('patch')

                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    @include('components.message')


                    <div class="form-group">
                        <label for="title" class="col-lg-12 control-label">Title</label>
                        <div class="col-lg-12">
                            <input type="text" class="form-control" id="title" placeholder="Title" name="title" value="{{old('title') ? old('title') : $post->title}}">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="content" class="col-lg-12 control-label">Content</label>
                        <div class="col-lg-12">
                            <textarea class="form-control" rows="3" id="content" name="content" value="{{old('content') ? old('content') : $post->content}}">{{ $post->content }}</textarea>
                        </div>
                    </div>


                    <div class="form-group">
                        <label for="categories" class="col-lg-12 control-label">Categories</label>

                        <div class="col-lg-12">
                            <select class="form-control" id="category" name="categories[]" multiple>

                                @foreach($categories as $category)
                                    <option value="{{ $category->id }}"  @if(in_array($category->id, $selectedCategories))
                                    selected="selected" style="background-color: green;" @endif >{{ $category->name }}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="col-lg-12" style="background-color: lightblue">

                        @if ( count($post->images ) > 0)

                            @foreach($post->images as $image)
                                <img src="{{ Storage::url($image->title) }}" class="img-fluid" style="width: 50%;height:300px">
                                <div class="form-group">
                                    Cambia Immagine
                                    <input type="file" name="imageEdit" class="form-control">
                                </div>
                            @endforeach

                        @else

                            <div class="form-group">
                                Aggiungi Immagine
                                <input type="file" name="imageAdd" class="form-control">
                            </div>

                        @endif



                    </div>

                    <div class="form-group">
                        <div class="col-lg-10 col-lg-offset-2">
                            <button type="reset" class="btn btn-default">Cancel</button>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/posts/index.blade.php
@extends('layouts.app')

@section('content')
 <div class="container col-md-10 col-md-offset-2">
        <div class="mt-5 card">
            <div class="card-header">
                <h5 class="float-left">All posts</h5>
                @include('admin.components.redirect')
                <div class="clearfix"></div>
            </div>
            <div class="content">

                @include('components.message')

                @if ($posts->isEmpty())
                    <p> There is no post.</p>
                @else
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Image</th>
                                <th>Title</th>
                                <th>Slug</th>
                                <th>Created At</th>
                                <th>Updated At</th>
                                <th>action</th>

                            </tr>
                            </thead>
                            <tbody>
                            @foreach($posts as $post)
                                <tr>
                                    <td>{{ $post->id }}</td>
                                    <td>

                                        @foreach($post->images as $image)
                                            <img src="{{ Storage::url($image->title) }}" class="img-fluid" style="width: 150px;height:100%">
                                        @endforeach

                                    </td>
                                    <td>
                                        <a href="{{ route('admin.posts.edit',$post) }}">{{ $post->title }} </a>
                                    </td>
                                    <td>{{ $post->slug }}</td>
                                    <td>{{ $post->created_at }}</td>
                                    <td>{{ $post->updated_at }}</td>
                                    <td>
                                        <form  style="display: inline-block" method="POST" action="{{ route('admin.posts.destroy',$post) }}">
                                            @csrf
                                            @method('delete')

                                            <button type="submit"  class="">
                                                <i class="fas fa-trash-alt"></i>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                @endif
				</div>
        </div>
    </div>
@endsection

resources/views/admin/posts/today.blade.php
@extends('layouts.app')

@section('content')
 <div class="container col-md-10 col-md-offset-2">
        <div class="card mt-5">
            <div class="card-header">
                <h5 class="float-left">All posts of today</h5>
                @include('admin.components.redirect')
                <div class="clearfix"></div>
            </div>
            <div class="content">

                <form action="{{ route('admin.selectDayPosts') }}" method="post">
                    @csrf

                    <div class="form-group">

                        <div class="col-lg-10 col-lg-offset-2">
                            <input type="date" name="dayPost" id="">

                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>

                </form>

                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>ID</th>
                                <th>Title</th>
                                <th>Slug</th>
                                <th>Cateogires Number</th>
                                <th>Comments Number</th>
                                <th>Created At</th>
                                <th>Updated At</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($posts as $post)
                                <tr>
                                    <td>{{ $post->id }}</td>
                                    <td>  {{ $post->title }}  </td>
                                    <td>{{ $post->slug }}</td>
                                    <td><span class="badge"> {{ $post->categories_count}}</span></td>
                                    <td><span class="badge"> {{ $post->comments_count}}</span></td>
                                    <td>{{ $post->created_at }}</td>
                                    <td>{{ $post->updated_at }}</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
				</div>
        </div>
    </div>
@endsection