routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::auth();
Route::get('/', 'PageController@index')->name('home');
Route::get('/contact', 'PageController@contact')->name('contact');

Route::get('/admin', 'PageController@adminHome')->middleware('manager')->name('admin');



Route::prefix('admin-users-managment')->namespace('Admin')->name('admin.')->middleware('admin')->group( function () // ->middleware('manager') php artisan make:middleware manager
{
    Route::resource('users', 'UsersController');
});


Route::prefix('roles-managment')->namespace('Admin')->name('admin.')->middleware('manager')->group( function () //php artisan make:middleware manager
{
    Route::resource('roles', 'RolesController');
});


Route::prefix('admin-posts-managment')->namespace('Admin')->name('admin.')->middleware('manager')->group( function ()
{
    Route::resource('posts', 'PostsController');
    Route::get('/todayPosts','PostsController@getToday')->name('todayPosts');
    Route::post('/selectDayPosts','PostsController@selectDayPosts')->name('selectDayPosts');
});


Route::prefix('admin-categories-managment')->namespace('Admin')->name('admin.')->middleware('manager')->group( function ()
{
    Route::resource('categories', 'CategoryController');
});


Route::prefix('user-commentsAndPost')->namespace('User')->name('user.')->middleware('auth')->group( function ()
{
    Route::get('/create', 'PostsController@create')->name('create');
    Route::post('/store', 'PostsController@store')->name('store');
    Route::get('/show/{post}', 'PostsController@show')->middleware('auth')->name('show');
    Route::post('/commentsStore/{post}', 'CommentsController@store')->name('commentsStore');

});


Route::prefix('userSection')->namespace('User')->name('userSection.')->middleware('auth')->group( function ()
{
    Route::resource('posts','UserPostController');
});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title> @yield('title') </title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="{{ asset('js/clean-blog.min.js') }}" defer></script>

     <!-- Custom fonts for this template -->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>


    <!-- Styles -->
    <link href="{{ asset('css/clean-blog.min.css') }}" rel="stylesheet">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/fontawesome-free/css/all.min.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
          <div class="container">

            <a class="navbar-brand" href="/">BLOG</a>

            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
              Menu
              <i class="fas fa-bars"></i>
            </button>

            <div class="collapse navbar-collapse" id="navbarResponsive">

              <ul class="ml-auto navbar-nav">

                <li class="nav-item">
                  <a class="nav-link" href="/contact">Contact</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{{ route('user.create') }}">Crea un nuovo post</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{{ route('userSection.posts.index') }}">Profilo</a>
                </li>

                @if (!Auth::check())

                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                    </li>

                @else
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }}
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('logout') }}"
                                onclick="event.preventDefault();
                                                document.getElementById('logout-form').submit();">
                                Logout
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                @csrf
                            </form>
                        </div>

                    </li>

                    @if(Auth::user()->hasRole('manager') || Auth::user()->hasRole('admin'))
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                Gestione
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('admin') }}">
                                    Admin
                                </a>

                                <a class="dropdown-item" href="{{ route('admin.todayPosts') }}">
                                    post creati oggi
                                </a>

                            </div>
                        </li>
                    @endif

                @endif


               </ul>

            </div>
          </div>
        </nav>


  <header class="masthead" style="background-image: url({{ asset('img/home-bg.jpg') }})">
    <div class="overlay"></div>

    <div class="container">
      <div class="row">
        <div class="mx-auto col-lg-8 col-md-10">
          <div class="site-heading">
            <h1>Clean Blog</h1>
            <span class="subheading">A Blog Theme by Start Bootstrap</span>
          </div>
        </div>
      </div>
    </div>

  </header>


        <main class="py-4">
            @yield('content')
        </main>

        <footer>
            <div class="container">
              <div class="row">
                <div class="mx-auto col-lg-8 col-md-10">
                  <ul class="text-center list-inline">
                    <li class="list-inline-item">
                      <a href="#">
                        <span class="fa-stack fa-lg">
                          <i class="fas fa-circle fa-stack-2x"></i>
                          <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                        </span>
                      </a>
                    </li>
                    <li class="list-inline-item">
                      <a href="#">
                        <span class="fa-stack fa-lg">
                          <i class="fas fa-circle fa-stack-2x"></i>
                          <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                        </span>
                      </a>
                    </li>
                    <li class="list-inline-item">
                      <a href="#">
                        <span class="fa-stack fa-lg">
                          <i class="fas fa-circle fa-stack-2x"></i>
                          <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                        </span>
                      </a>
                    </li>
                  </ul>
                  <p class="copyright text-muted">Copyright &copy; Your Website 2020</p>
                </div>
              </div>
            </div>
          </footer>
    </div>
</body>
</html>