routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::auth();
Route::get('/', 'PageController@index')->name('home');
Route::get('/contact', 'PageController@contact')->name('contact');

Route::get('/admin', 'PageController@adminHome')->middleware('manager')->name('admin');



Route::prefix('admin-users-managment')->namespace('Admin')->name('admin.')->middleware('admin')->group( function () // ->middleware('manager') php artisan make:middleware manager
{
    Route::resource('users', 'UsersController');
});


Route::prefix('roles-managment')->namespace('Admin')->name('admin.')->middleware('manager')->group( function () //php artisan make:middleware manager
{
    Route::resource('roles', 'RolesController');
});


Route::prefix('admin-posts-managment')->namespace('Admin')->name('admin.')->middleware('manager')->group( function ()
{
    Route::resource('posts', 'PostsController');
    Route::get('/todayPosts','PostsController@getToday')->name('todayPosts');
    Route::post('/selectDayPosts','PostsController@selectDayPosts')->name('selectDayPosts');
});


Route::prefix('admin-categories-managment')->namespace('Admin')->name('admin.')->middleware('manager')->group( function ()
{
    Route::resource('categories', 'CategoryController');
});


Route::prefix('user-commentsAndPost')->namespace('User')->name('user.')->middleware('auth')->group( function ()
{
    Route::get('/create', 'PostsController@create')->name('create');
    Route::post('/store', 'PostsController@store')->name('store');
    Route::get('/show/{post}', 'PostsController@show')->middleware('auth')->name('show');
    Route::post('/commentsStore/{post}', 'CommentsController@store')->name('commentsStore');

});


Route::prefix('userSection')->namespace('User')->name('userSection.')->middleware('auth')->group( function ()
{
    Route::resource('posts','UserPostController');
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

use Spatie\Permission\Traits\HasRoles; //per i ruoli di alravel permission vai in config.app per vedere come fare mette automaticamente la relazione roles()

class User extends Authenticatable
{
    use Notifiable,HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','slug'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    public function posts()
    {
        return $this->hasMany('App\Models\Post');
    }

    public function comments()
    {
        return $this->hasMany('App\Models\Comments');
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }
}

app/Http/Controllers/Admin/PostsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\PostEditRequest;
use App\Http\Requests\PostFormRequest;
use App\Models\Category;
use App\Models\Image;
use App\Models\Post;
use App\Traits\ImgManageTrait;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class PostsController extends Controller
{
    use ImgManageTrait;

    public function getToday()
    {

        $posts = Post::selectDay(Carbon::today());

        return view('admin.posts.today',compact('posts'));
    }

    public function selectDayPosts(Request $request)
    {
        $day = $request->dayPost;

        $carbonDate = Carbon::parse($day);

        $posts = Post::selectDay($carbonDate);

        return view('admin.posts.today',compact('posts'));
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::with('categories')->get();

        return view('admin.posts.index',compact('posts'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {

        if(!$post)
        {
            $errors =
            [
                'error_message' => 'Post non trovato'
            ];
            session()->flash('error',$errors);
            return redirect()->back();
        }

        $categories = Category::all();
        $selectedCategories = $post->categories->pluck('id')->toArray();
        return view('admin.posts.edit',compact('post','categories','selectedCategories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PostEditRequest $request, Post $post)
    {

        try
        {
            DB::beginTransaction();

                $post->title = $request->title;
                $post->content = $request->content;


                $post->categories()->sync($request->categories);

                if($request->hasFile('imageEdit'))
                {

                    $image = Image::where('post_id',$post->id)->firstOrFail();
                    $this->editImage($request->imageEdit,$post,$image );
                }

                if($request->hasFile('imageAdd'))
                {
                    $this->addImage($request->imageAdd, $post);
                }

                $updated = $post->save();

            DB::commit();

                session()->flash('success',('Post mofificato con successo'));
                return redirect()->route('admin.posts.index');
        }
        catch(\Exception $e)
        {
            $errors =
            [
                'error_message' => 'Errore nella modifica del post',
            ];
            session()->flash('error',($errors));
            return redirect()->route('admin.posts.index');
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        try
        {
            DB::beginTransaction();

                foreach($post->images as $image)
                {
                    if(file_exists( public_path('storage/'.$image->title) ) )
                    {
                        unlink(public_path('storage/'.$image->title));
                    }
                }
                Image::where('post_id',$post->id)->delete();
                $deleted = $post->delete();


            DB::commit();

                session()->flash('success',('Post cancellato con successo'));
                return redirect()->route('admin.posts.index');
        }
        catch(\Exception $e)
        {
            $errors =
            [
                'error_message' => 'Errore nella rimozione del post',
            ];
            session()->flash('error',($errors));
            return redirect()->route('admin.posts.index');
        }

    }
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use App\Http\Requests\UserEditFormRequest;
use Spatie\Permission\Models\Role;
use Illuminate\Support\Facades\Hash;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view('admin.user.index',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {

        if(!$user)
        {
            $errors =
            [
                'error_message' => 'User non trovato'
            ];
            session()->flash('error',$errors);
            return redirect()->back();
        }

        $roles = Role::all();
        $selectedRoles = $user->roles()->pluck('name')->toArray();

        return view('admin.user.edit',compact('user','roles','selectedRoles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserEditFormRequest $request, User $user)
    {
        try
        {
            DB::beginTransaction();

                $user->name = $request->name;
                $user->email = $request->email;

                if($request->password != null)
                {
                    $user->password = Hash::make($request->password);
                }

                $user->syncRoles($request->role); //syncRoles rimuove tutti i ruoli inseriti e aggiunge quello appena inserito
                $user->save();

            DB::commit();

                session()->flash('success',('Utente mofificato con successo'));
                return redirect()->route('admin.users.edit',$user);
        }
        catch(\Exception $e)
        {
            $errors =
            [
                'error_message' => 'Errore nella modifica del utente',
            ];
            session()->flash('error',($errors));
            return redirect()->route('admin.users.edit',$user);
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/User/CommentsController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Http\Requests\CommentFormRequest;
use App\Models\Comment;
use App\Models\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class CommentsController extends Controller
{

    public function store(CommentFormRequest $request,Post $post)
    {

        try
        {
            DB::beginTransaction();

                $user = Auth::user();

                $comment = Comment::create(
                    [
                        'post_id' => $post->id,
                        'content' => $request->content,
                        'user_id' => $user->id,
                    ]
                );

            DB::commit();

                session()->flash('success','commento creato con successo');
                return redirect()->back();
        }
        catch(\Exception $e)
        {
            $errors =
            [
                'error_message' => 'Non è stato possibile creare il commento'
            ];
            session()->flash('error',$errors);
            return redirect()->back();
        }

    }

}

app/Http/Controllers/User/ImageController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Image;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class ImageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('post.image.imageUpload');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        try
        {
            DB::beginTransaction();

                if($request->hasFile('image'))
                {
                    $this->validate($request,
                    [
                        'image' =>'required|image|mimes:jpeg,png,jpg',
                    ]);
                }

                $imageName = time(). '.' .$request->image->extension();

                $request->image->move (public_path('articoli/img'),$imageName );

                $image = Image::create([

                    'title' => 'http://localhost:8000/articoli/img/'. $imageName,
                    'post_id'   => 1,

                ]);

            DB::commit();

                session()->flash('success','immagine creata con successo');
                return redirect()->back();
        }
        catch(\Exception $e)
        {
            $errors =
            [
                'error_message' => 'Non è stato possibile aggiungere l\'immagine',
            ];
            session()->flash('error',$errors);
            return redirect()->back();
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/User/PostsController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Http\Requests\PostFormRequest;
use App\Models\Category;
use App\Models\Image;
use App\Models\Post;
use App\Traits\ImgManageTrait;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Validation\Rules\Unique;

class PostsController extends Controller
{

    use ImgManageTrait;


    public function create()
    {
        try
        {
            DB::beginTransaction();

                $categories = Category::all();

            DB::commit();

                return view('post.create',compact('categories'));
        }
        catch(\Exception $e)
        {

            $errors =
            [
                'error_message' => 'Errore nella creazione del post',
            ];
            session()->flash('error',($errors));
            return redirect()->route('home');
        }
    }


    public function store(PostFormRequest $request)
    {

        try
        {
            DB::beginTransaction();

                $user = Auth::user();

                $post = $user->posts()->create(
                [
                    'title'     => $request->title,
                    'content'   => $request->content,
                    'slug'      => uniqid(),
                ]);

                $post->categories()->sync($request->categories);

                if($request->hasFile('image'))
                {
                    $this->addImage($request->image, $post);
                }

            DB::commit();

                session()->flash('success',('Post creato con successo'));
                return redirect()->route('home');
        }
        catch(\Exception $e)
        {
            $errors =
            [
                'error_message' => 'Errore nella creazione del post',
            ];
            session()->flash('error',($errors));
            return redirect()->route('home');
        }

    }


    public function show( Post $post)
    {

        if(!$post)
        {
            $errors =
            [
                'error_message' => 'Post non trovato'
            ];
            session()->flash('error',$errors);
            return redirect()->route('home');
        }

        return view('post.show',compact('post'));
    }
}

resources/views/user/post/edit.blade.php
@extends('layouts.app')

@section('content')
  <div class="container col-md-10 col-md-offset-2">
        <div class="mt-5 card">
            <div class="card-header ">
                <h5 class="float-left">Edit a post</h5>
                <div class="clearfix"></div>
            </div>
            <div class="mt-2 card-body">
                <form method="post" action="{{ route('userSection.posts.update',$post) }}"  enctype="multipart/form-data">
                    @csrf
                    @method('patch')

                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    @include('components.message')


                    <div class="form-group">
                        <label for="title" class="col-lg-12 control-label">Title</label>
                        <div class="col-lg-12">
                            <input type="text" class="form-control" id="title" placeholder="Title" name="title" value="{{old('title') ? old('title') : $post->title}}">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="content" class="col-lg-12 control-label">Content</label>
                        <div class="col-lg-12">
                            <textarea class="form-control" rows="3" id="content" name="content" value="{{old('content') ? old('content') : $post->content}}">{{ $post->content }}</textarea>
                        </div>
                    </div>


                    <div class="form-group">
                        <label for="categories" class="col-lg-12 control-label">Categories</label>

                        <div class="col-lg-12">
                            <select class="form-control" id="category" name="categories[]" multiple>

                                @foreach($categories as $category)
                                    <option value="{{ $category->id }}"  @if(in_array($category->id, $selectedCategories))
                                    selected="selected" style="background-color: green;" @endif >{{ $category->name }}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="col-lg-12" style="background-color: lightblue">

                        @if ( count($post->images ) > 0)

                            @foreach($post->images as $image)
                                <img src="{{ Storage::url($image->title) }}" class="img-fluid" style="width: 50%;height:300px">
                                <div class="form-group">
                                    Cambia Immagine
                                    <input type="file" name="imageEdit" class="form-control">
                                </div>
                            @endforeach

                        @else

                            <div class="form-group">
                                Aggiungi Immagine
                                <input type="file" name="imageAdd" class="form-control">
                            </div>

                        @endif



                    </div>

                    <div class="form-group">
                        <div class="col-lg-10 col-lg-offset-2">
                            <button type="reset" class="btn btn-default">Cancel</button>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
        <a href="{{ route('admin.posts.index') }}"> Torna alla lista</a>
    </div>
@endsection

resources/views/user/post/show.blade.php
@extends('layouts.app')
@section('title', $post->title)
@section('content')

    <header class="masthead" style="background-image: url({{url('/img/post-bg.jpg')}})">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="page-heading">
                        <h1>{{$post->title}}</h1>
                        <span class="subheading">
                            <p class="post-meta">Posted by <a style="color:white" href="#">{{$post->user->name}}</a> on {{$post->created_at->format('d-m-Y')}}
                                Categories:
                                @foreach($post->categories as $category)
                                    {{$category->name}}
                                @endforeach
                            </p>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <article>
        <div class="container">

            <div class="col-lg-8 col-md-10 mx-auto text-center">
                <h2> Il mio post</h2>

                <div class="list-group-item">
                    <div class="row-content">
                        <h5><i class="fas fa-file-signature mb-3"></i> Manage Posts</h5>
                        <a href="{{ route('userSection.posts.edit',$post) }}" class="btn btn-info">Modifica</a>

                        <form  style="display: inline-block" method="POST" action="{{ route('userSection.posts.destroy',$post) }}">
                            @csrf
                            @method('delete')

                            <button type="submit"  class="btn btn-success">
                                Elimina
                            </button>
                        </form>

                    </div>
                </div>

                <div class="card-body">

                    @foreach($post->images as $image)
                        <img src="{{ Storage::url($image->title) }}" class="img-fluid" style="width: 100%;height:300px">
                    @endforeach
                    <p>{{ $post->content }}</p>

                </div>
                <div class="clearfix"></div>
            </div>

            @foreach($post->comments as $comment)
                <div class="col-lg-8 col-md-10 mx-auto card mb-4">
                    <div class="card-body">
                        <blockquote>{{ $comment->content }}</blockquote>
                    </div>
                </div>
            @endforeach

            <div class="col-lg-8 col-md-10 mx-auto card">
                <div class="card-body">
                    <form method="post" action="{{ route('user.commentsStore',$post) }}">
                        @csrf

                        @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                        @endif

                        @include('components.message')

                        <div class="form-group">
                            <legend>Comment</legend>
                        </div>

                        <div class="form-group">
                            <div class="col-lg-12">
                                <textarea class="form-control" rows="3" id="content" name="content" value="{{ old('content') }}"></textarea>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-lg-10 col-lg-offset-2">
                                <button type="submit" class="btn btn-primary">Post</button>
                            </div>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </article>
@endsection